# Generated by Django 2.1.5 on 2019-03-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerySystem', '0003_auto_20190307_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
