# Generated by Django 2.1.5 on 2019-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerySystem', '0004_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
